# Set this to true to enable Kubernetes RBAC support (recommended)
rbac:
  enabled: false

# Image configuration
registry: deis
name: brigade-github-app
tag: latest
pullPolicy: "Always"

service:
  name: brigade-github-app
  type: ClusterIP
  externalPort: 80
  internalPort: 7746

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - gh-app.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: gh-app-tls
      hosts:
      - gh-app.example.com

gateway:
  # The author associations who are allowed to have PRs built
  # Classes are: COLLABORATOR, CONTRIBUTOR, OWNER, NONE, MEMBER, FIRST_TIMER, FIRST_TME_CONTRIBUTOR
  # See https://developer.github.com/v4/enum/commentauthorassociation/
  # To completely disable pull request builds, leave this list blank.
  allowedAuthorRoles:
    - OWNER
    - MEMBER
    - COLLABORATOR

github:
  # The x509 PEM-formatted keyfile GitHub issued for you App.
  key: |
    REQUIRED: Your key goes here.
  # This represents the unique ID for a GitHub App
  # The value can be retrieved from the main App page or any inbound webhook payloads
  appID:
  # Trigger a Check Suite on Pull Requests
  # This will need to be set to true to enable running Check Suites on PRs originating from forks
  checkSuiteOnPR: true