{{ $fullname :=  include "gateway.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: gateway
    type: github-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        role: gateway
        release: "{{ .Release.Name }}"
        type: github-app
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BRIGADE_AUTHORS
            value: {{ if .Values.gateway.allowedAuthorRoles }}{{ join "," .Values.gateway.allowedAuthorRoles | quote }}{{ end }}
          - name: GATEWAY_CONFIG
            value: "/etc/brigade-github-app/key.pem"
          - name: APP_ID
            value: "{{ .Values.github.appID }}"
          - name: CHECK_SUITE_ON_PR
            value: "{{ .Values.github.checkSuiteOnPR }}"
        volumeMounts:
          - name: github-config
            mountPath: /etc/brigade-github-app
      volumes:
        - name: github-config
          configMap:
            name: {{ $fullname }}
